# Tests for the lookup tables in classifications/.
#
# These are the tables the preparation joins onto the data: the consumer price
# index, the contribution assessment ceiling (Beitragsbemessungsgrenze) and the
# marginal part-time income threshold (Geringfuegigkeitsgrenze). They are
# generated by classifications/build_statutory_tables.R out of the Stata
# reference. Nothing downstream checks that a join found a match, so a missing
# year here becomes a silent column of NA in the panel. That is what these
# tests are for.

covered_years <- 1975:2024

read_classification <- function(file) {
  readr::read_csv(here::here("classifications", file), show_col_types = FALSE)
}

#====================================================================
#  Consumer price index
#====================================================================

test_that("cpi.csv has exactly one row per year from 1975 to 2024", {
  cpi <- read_classification("cpi.csv")
  expect_named(cpi, c("year", "cpi"))
  expect_equal(sort(cpi$year), covered_years)
  expect_false(any(is.na(cpi)))
})

test_that("cpi.csv is a 2015-base index", {
  cpi <- read_classification("cpi.csv")
  expect_equal(cpi$cpi[cpi$year == 2015], 100)
})

test_that("cpi.csv moves plausibly year on year", {
  cpi <- read_classification("cpi.csv")[order(read_classification("cpi.csv")$year), ]
  expect_true(all(cpi$cpi > 0))
  # 1986 is the one year the German index fell, so the series is not monotone.
  # Any step larger than 15 percent would be a transcription error, not inflation.
  expect_true(all(abs(diff(cpi$cpi) / head(cpi$cpi, -1)) < 0.15))
})

#====================================================================
#  Statutory limits, both split East and West
#====================================================================

statutory <- list(
  wa_ceiling     = list(file = "wa_ceiling.csv",     value = "limit_assess"),
  limit_marginal = list(file = "limit_marginal.csv", value = "limit_marginal")
)

for (nm in names(statutory)) {
  spec <- statutory[[nm]]

  test_that(paste0(spec$file, " has one row per year and Rechtskreis, 1975 to 2024"), {
    tab <- read_classification(spec$file)
    expect_named(tab, c("year", "east", spec$value))
    expect_setequal(unique(tab$east), c(0, 1))
    expect_equal(nrow(tab), 2 * length(covered_years))
    expect_equal(sort(unique(tab$year)), covered_years)
    expect_equal(nrow(dplyr::distinct(tab, year, east)), nrow(tab))
    expect_false(any(is.na(tab)))
    expect_true(all(tab[[spec$value]] > 0))
  })

  test_that(paste0(spec$file, " gives East and West the same value before 1992"), {
    tab <- read_classification(spec$file)
    before <- tab[tab$year < 1992, ]
    wide <- tidyr::pivot_wider(before, names_from = "east", values_from = spec$value)
    expect_equal(wide[["0"]], wide[["1"]])
  })
}

test_that("the ceiling split opens in 1992 and never closes, the marginal one closes in 1999", {
  # Both limits were unified for the old Federal Republic and split with the
  # 1992 Rechtskreis Ost. The Geringfuegigkeitsgrenze was levelled again from
  # 1999; the Beitragsbemessungsgrenze still differs in 2024.
  ceiling <- read_classification("wa_ceiling.csv") |>
    tidyr::pivot_wider(names_from = "east", values_from = "limit_assess")
  split_ceiling <- ceiling$year[ceiling[["0"]] != ceiling[["1"]]]
  expect_equal(split_ceiling, 1992:2024)

  marginal <- read_classification("limit_marginal.csv") |>
    tidyr::pivot_wider(names_from = "east", values_from = "limit_marginal")
  split_marginal <- marginal$year[marginal[["0"]] != marginal[["1"]]]
  expect_equal(split_marginal, 1992:1998)
})

test_that("the statutory limits are daily figures, not monthly or annual", {
  # Both csv files hold euro per day. A West ceiling of about 50 in 1975 and
  # about 260 in 2024 is the right order of magnitude; a monthly figure would
  # be thirty times larger.
  ceiling <- read_classification("wa_ceiling.csv")
  west_2024 <- ceiling$limit_assess[ceiling$year == 2024 & ceiling$east == 0]
  expect_gt(west_2024, 100)
  expect_lt(west_2024, 500)
})

#====================================================================
#  Occupation crosswalks
#====================================================================

test_that("the occupation crosswalks map each source code exactly once", {
  kldb <- read_classification("kldb88_beruf.csv")
  expect_equal(nrow(dplyr::distinct(kldb, !!rlang::sym(names(kldb)[1]))), nrow(kldb))

  blo <- read_classification("walkover_beruf_occblo.csv")
  expect_equal(nrow(dplyr::distinct(blo, !!rlang::sym(names(blo)[1]))), nrow(blo))
})
